<?php

declare(strict_types=1);

namespace Katalam\OpenImmo\Services;

use DateTime;
use GoetasWebservices\XML\XSDReader\Schema\Type\ComplexType;
use GoetasWebservices\XML\XSDReader\Schema\Type\ComplexTypeSimpleContent;
use GoetasWebservices\XML\XSDReader\Schema\Type\Type;
use InvalidArgumentException;
use Nette\PhpGenerator\Property;

class TypeUtil
{
    public const OPENIMMO_NAMESPACE = 'Katalam\\OpenImmo\\Dtos\\';

    public static function getTypeForSerializer(string $type): string
    {
        $isPlural = str_ends_with($type, '[]');
        $singular = str_replace('[]', '', $type);
        switch ($singular) {
            case 'string':
            case 'float':
            case 'int':
            case 'array':
                $type = $singular;
                break;

            case 'positiveInteger':
                $type = 'int';
                break;

            case 'bool':
            case 'boolean':
                $type = 'bool';
                break;

            case 'dateTime':
            case DateTime::class:
                $type = 'DateTime<\'Y-m-d\TH:i:s\', null, [\'Y-m-d\TH:i:sP\', \'Y-m-d\TH:i:s\']>';
                break;

            case 'date':
                $type = 'DateTime<\'Y-m-d\'>';
                break;

            case 'decimal':
                $type = 'float';
                break;

            case 'kontakt':
            case 'base64Binary':
                $type = 'string';
                break;

            default:
                $ns = self::OPENIMMO_NAMESPACE;
                $type = $ns.$singular;
                break;
        }

        if ($isPlural) {
            return 'array<'.$type.'>';
        }

        return $type;
    }

    public static function getValidPhpType(string $propertyType): string
    {
        $isPlural = str_ends_with($propertyType, '[]');
        if ($isPlural) {
            return 'array';
        }

        switch ($propertyType) {
            case 'decimal':
            case 'float':
                $propertyType = 'float';
                break;

            case 'bool':
            case 'boolean':
                $propertyType = 'bool';
                break;

            case 'int':
            case 'positiveInteger':
            case 'PositiveIntegerType':
                $propertyType = 'int';
                break;

            case 'date':
            case 'dateTime':
            case '\\'.DateTime::class:
                $propertyType = '\\'.DateTime::class;
                break;

            case 'string':
            case 'kontakt':
            case 'base64Binary':
                $propertyType = 'string';
                break;

            case 'array':
                $propertyType = 'array';
                break;

            default:
                $className = '\\'.self::OPENIMMO_NAMESPACE.$propertyType;
                $propertyType = $className;
        }

        return $propertyType;
    }

    public static function getDefaultValueForType(string $propertyType, bool $nullable): float|false|int|array|string|null
    {
        $defaultValue = match ($propertyType) {
            'float' => 0.0,
            'bool' => false,
            'int' => 0,
            'string' => '',
            'array' => [],
            default => str_ends_with($propertyType, '[]') ? [] : null,
        };

        return $nullable ? null : $defaultValue;
    }

    public static function extractTypeForPhp(Type $typeFromXsd, ?string $propertyName = null): ?string
    {
        $type = 'string';

        if (($typeFromXsd->getName() ?? '') !== '') {
            $type = $typeFromXsd->getName();
        } elseif ($typeFromXsd instanceof ComplexType) {
            if ($propertyName !== null) {
                return ucfirst($propertyName);
            }
        } elseif ($typeFromXsd instanceof ComplexTypeSimpleContent) {
            // is default string
        } elseif ($typeFromXsd->getRestriction()->getBase() !== '') {
            $type = $typeFromXsd->getRestriction()->getBase()->getName();
        }

        return $type;
    }

    public static function isConstantsBasedProperty(Property $property): bool
    {
        return strtoupper($property->getName()).'_* constants' === CodeGenUtil::getAnnotationFromProperty($property, 'see');
    }

    public static function translateClass(string $key): string
    {
        return match ($key) {
            'Aktion' => 'Action',
            'Alter' => 'Age',
            'Anbieter' => 'Provider',
            'AngeschlGastronomie' => 'AttachedGastronomy',
            'Anhaenge' => 'Attachments',
            'Anhang' => 'Attachment',
            'Ausbaustufe' => 'DevelopmentStage',
            'Ausblick' => 'View',
            'AusrichtBalkonTerrasse' => 'BalconyTerraceOrientation',
            'AussenCourtage' => 'ExternalCommission',
            'Ausstattung' => 'Equipment',
            'Bad' => 'Bathroom',
            'Bauweise' => 'ConstructionMethod',
            'BebaubarNach' => 'DevelopableAccordingTo',
            'Befeuerung' => 'HeatingSystem',
            'Betriebskostennetto' => 'NetOperatingCosts',
            'Bewertung' => 'Evaluation',
            'Bieterverfahren' => 'BiddingProcess',
            'Boden' => 'Floor',
            'BreitbandZugang' => 'BroadbandAccess',
            'BueroPraxen' => 'OfficePractices',
            'Check' => 'Check',
            'Dachform' => 'RoofShape',
            'Daten' => 'Data',
            'Distanzen' => 'Distances',
            'DistanzenSport' => 'SportDistances',
            'Einzelhandel' => 'Retail',
            'EmailSonstige' => 'OtherEmail',
            'Energiepass' => 'EnergyPerformanceCertificate',
            'Energietyp' => 'EnergyType',
            'Erschliessung' => 'Development',
            'ErschliessungUmfang' => 'DevelopmentScope',
            'Evbnetto' => 'NetEVB',
            'Fahrstuhl' => 'Elevator',
            'Feld' => 'Field',
            'Flaechen' => 'Areas',
            'Foto' => 'Photo',
            'Freitexte' => 'FreeTexts',
            'FreizeitimmobilieGewerblich' => 'CommercialLeisureProperty',
            'Gastgewerbe' => 'Hospitality',
            'Geo' => 'Geo',
            'Geokoordinaten' => 'GeoCoordinates',
            'Gesamtbelastungnetto' => 'NetTotalCost',
            'Gesamtkostenprom2von' => 'TotalCostsPerSqmFrom',
            'Gesamtmietenetto' => 'NetTotalRent',
            'Geschlecht' => 'Gender',
            'Grundstueck' => 'Plot',
            'HallenLagerProd' => 'HallsStorageProduction',
            'Hauptmietzinsnetto' => 'NetMainRent',
            'Haus' => 'House',
            'Heizkostennetto' => 'NetHeatingCosts',
            'Heizungsart' => 'HeatingType',
            'Immobilie' => 'RealEstate',
            'ImpressumStrukt' => 'ImprintStructure',
            'Infrastruktur' => 'Infrastructure',
            'InnenCourtage' => 'InternalCommission',
            'Kaufpreis' => 'PurchasePrice',
            'Kaufpreisnetto' => 'NetPurchasePrice',
            'Kontaktperson' => 'ContactPerson',
            'Kueche' => 'Kitchen',
            'LageGebiet' => 'LocationArea',
            'LageImBau' => 'LocationInBuilding',
            'Land' => 'Country',
            'LandUndForstwirtschaft' => 'AgricultureAndForestry',
            'Master' => 'Master',
            'MaxMietdauer' => 'MaxRentalPeriod',
            'MieteinnahmenIst' => 'ActualRentalIncome',
            'MieteinnahmenSoll' => 'TargetRentalIncome',
            'MinMietdauer' => 'MinRentalPeriod',
            'Moebliert' => 'Furnished',
            'Monatlichekostennetto' => 'NetMonthlyCosts',
            'Nebenkostenprom2von' => 'AdditionalCostsPerSqmFrom',
            'Nettomieteprom2von' => 'NetRentPerSqmFrom',
            'Nutzungsart' => 'TypeOfUse',
            'ObjektText' => 'PropertyText',
            'Objektart' => 'PropertyType',
            'Objektkategorie' => 'PropertyCategory',
            'Openimmo' => 'OpenImmo',
            'Parken' => 'Parking',
            'PreisZeiteinheit' => 'PriceTimeUnit',
            'Preise' => 'Prices',
            'ProvisionTeilen' => 'CommissionSplit',
            'Provisionnetto' => 'NetCommission',
            'Ruecklagenetto' => 'NetReserves',
            'Serviceleistungen' => 'Services',
            'Sicherheitstechnik' => 'SecurityTechnology',
            'Sonstige' => 'Other',
            'Sonstigekostennetto' => 'NetOtherCosts',
            'Sonstigemietenetto' => 'NetOtherRent',
            'Stellplatzart' => 'ParkingSpaceType',
            'StpCarport' => 'ParkingCarport',
            'StpDuplex' => 'ParkingDuplex',
            'StpFreiplatz' => 'ParkingOutdoor',
            'StpGarage' => 'ParkingGarage',
            'StpParkhaus' => 'ParkingMultiStorey',
            'StpSonstige' => 'ParkingOther',
            'StpTiefgarage' => 'ParkingUnderground',
            'Summemietenetto' => 'NetTotalRent',
            'TelSonstige' => 'OtherPhone',
            'Uebertragung' => 'Transfer',
            'Unterkellert' => 'Basement',
            'UserDefinedAnyfield' => 'UserDefinedAnyfield',
            'UserDefinedExtend' => 'UserDefinedExtend',
            'UserDefinedSimplefield' => 'UserDefinedSimplefield',
            'Verkaufstatus' => 'SalesStatus',
            'Vermarktungsart' => 'MarketingType',
            'Versteigerung' => 'Auction',
            'VerwaltungObjekt' => 'PropertyManagement',
            'VerwaltungTechn' => 'TechnicalManagement',
            'Waehrung' => 'Currency',
            'WeitereAdresse' => 'AdditionalAddress',
            'Wohnung' => 'Apartment',
            'Zimmer' => 'Rooms',
            'ZinshausRenditeobjekt' => 'ApartmentBuildingInvestmentProperty',
            'Zustand' => 'Condition',
            'ZustandAngaben' => 'ConditionInformation',
            default => throw new InvalidArgumentException('Unknown key: '.$key),
        };
    }

    public static function translateAttributes(string $key): string
    {
        return match ($key) {
            'adressart' => 'addressType',
            'aktionart' => 'actionType',
            'alarmanlage' => 'alarmSystem',
            'alterAttr' => 'ageAttribute',
            'alternativ' => 'alternative',
            'anlage' => 'facility',
            'anzahl' => 'quantity',
            'art' => 'type',
            'aufAnfrage' => 'onRequest',
            'ausbauhaus' => 'expandableHouse',
            'bar' => 'cash',
            'bausatzhaus' => 'prefabricatedHouse',
            'bebaubarAttr' => 'developableAttribute',
            'bemerkung' => 'remark',
            'betreutesWohnen' => 'assistedLiving',
            'betriebskostenust' => 'operatingCostsVAT',
            'bidet' => 'bidet',
            'bioenergie' => 'bioEnergy',
            'blick' => 'view',
            'block' => 'block',
            'breitengrad' => 'latitude',
            'bueroTyp' => 'officeType',
            'carport' => 'carport',
            'catering' => 'catering',
            'ctype' => 'contentType',
            'dielen' => 'floorboards',
            'distanzZu' => 'distanceTo',
            'distanzZuSport' => 'distanceToSport',
            'doppelboden' => 'raisedFloor',
            'duplex' => 'duplex',
            'dusche' => 'shower',
            'ebk' => 'builtInKitchen',
            'einkauf' => 'shopping',
            'elektro' => 'electric',
            'emailart' => 'emailType',
            'erbpacht' => 'leasehold',
            'erdgasLeicht' => 'lightNaturalGas',
            'erdgasSchwer' => 'heavyNaturalGas',
            'erdwaerme' => 'geothermal',
            'erschlAttr' => 'developmentAttribute',
            'estrich' => 'screed',
            'etage' => 'floor',
            'evbust' => 'unitValueTaxVAT',
            'feldname' => 'fieldName',
            'fenster' => 'window',
            'fern' => 'remote',
            'fernwaermeDampf' => 'districtHeatingVapor',
            'fertigparkett' => 'finishedParquet',
            'fertigteile' => 'prefabricatedParts',
            'flachdach' => 'flatRoof',
            'fliesen' => 'tiles',
            'fluessiggas' => 'liquidGas',
            'freiplatz' => 'openSpace',
            'freizeitTyp' => 'leisureType',
            'fussboden' => 'flooring',
            'garage' => 'garage',
            'gas' => 'gas',
            'gastgewTyp' => 'hospitalityType',
            'gebiete' => 'areas',
            'gesamtbelastungust' => 'totalCostVAT',
            'gesamtkostenprom2bis' => 'totalCostsPerSqmTo',
            'gesamtmieteust' => 'totalRentVAT',
            'geschlAttr' => 'genderAttribute',
            'gewerbe' => 'commercial',
            'granit' => 'granite',
            'grundstTyp' => 'plotType',
            'gruppe' => 'group',
            'hallenTyp' => 'hallType',
            'handelTyp' => 'tradeType',
            'hauptmietzinsust' => 'mainRentVAT',
            'haustyp' => 'houseType',
            'heizkostenust' => 'heatingCostsVAT',
            'hinten' => 'rear',
            'holz' => 'wood',
            'hotelrestaurant' => 'hotelRestaurant',
            'isoLand' => 'isoCountry',
            'isoWaehrung' => 'isoCurrency',
            'kamera' => 'camera',
            'kauf' => 'purchase',
            'kaufpreisust' => 'purchasePriceVAT',
            'keller' => 'basement',
            'kfw40' => 'kfw40',
            'kfw55' => 'kfw55',
            'kfw60' => 'kfw60',
            'kfw70' => 'kfw70',
            'kohle' => 'coal',
            'krueppelwalmdach' => 'truncatedHipRoof',
            'kunststoff' => 'plastic',
            'kwkBio' => 'chpBio',
            'kwkErneuerbar' => 'chpRenewable',
            'kwkFossil' => 'chpFossil',
            'kwkRegenerativ' => 'chpRegenerative',
            'laengengrad' => 'longitude',
            'laminat' => 'laminate',
            'landTyp' => 'countryType',
            'lang' => 'long',
            'lasten' => 'encumbrances',
            'leasing' => 'leasing',
            'links' => 'left',
            'linoleum' => 'linoleum',
            'location' => 'location',
            'luftwp' => 'airHeatPump',
            'mansarddach' => 'mansardRoof',
            'marmor' => 'marble',
            'massiv' => 'solid',
            'maxDauer' => 'maxDuration',
            'mietePacht' => 'rentLease',
            'minDauer' => 'minDuration',
            'minergieZertifiziert' => 'minEnergieCertified',
            'minergiebauweise' => 'minEnergieConstruction',
            'mitMwst' => 'withVAT',
            'modus' => 'mode',
            'moeb' => 'furnished',
            'monatlichekostenust' => 'monthlyCostsVAT',
            'nahwaerme' => 'localHeating',
            'nebenkostenprom2bis' => 'additionalCostsPerSqmTo',
            'nettomieteprom2bis' => 'netRentPerSqmTo',
            'neubaustandard' => 'newBuildingStandard',
            'niedrigenergie' => 'lowEnergy',
            'nord' => 'north',
            'nordost' => 'northeast',
            'nordwest' => 'northwest',
            'oel' => 'oil',
            'ofen' => 'stove',
            'offen' => 'open',
            'ost' => 'east',
            'pantry' => 'pantry',
            'parkenTyp' => 'parkingType',
            'parkett' => 'parquet',
            'parkhaus' => 'parkingGarage',
            'passivhaus' => 'passiveHouse',
            'pellet' => 'pellet',
            'periode' => 'period',
            'personen' => 'persons',
            'pissoir' => 'urinal',
            'platzart' => 'spaceType',
            'polizeiruf' => 'policeCall',
            'provisionust' => 'commissionVAT',
            'pultdach' => 'shedRoof',
            'pyramidendach' => 'pyramidRoof',
            'rechts' => 'right',
            'regiId' => 'regionId',
            'reinigung' => 'cleaning',
            'ruecklageust' => 'reserveVAT',
            'satteldach' => 'saddleRoof',
            'schluesselfertigmitbodenplatte' => 'turnkeyWithFoundation',
            'schluesselfertigmitkeller' => 'turnkeyWithBasement',
            'schluesselfertigohnebodenplatte' => 'turnkeyWithoutFoundation',
            'sendersoftware' => 'senderSoftware',
            'senderversion' => 'senderVersion',
            'solar' => 'solar',
            'sonstigeTyp' => 'otherType',
            'sonstigekostenust' => 'otherCostsVAT',
            'sonstigemieteust' => 'otherRentVAT',
            'speed' => 'speed',
            'stand' => 'status',
            'stein' => 'stone',
            'stellplatzkaufpreis' => 'parkingSpacePurchasePrice',
            'stellplatzmiete' => 'parkingSpaceRent',
            'sued' => 'south',
            'suedost' => 'southeast',
            'suedwest' => 'southwest',
            'summemieteust' => 'totalRentVAT',
            'technEmail' => 'technicalEmail',
            'telefonart' => 'phoneType',
            'teppich' => 'carpet',
            'terrakotta' => 'terracotta',
            'tiefgarage' => 'undergroundParking',
            'timestamp' => 'timestamp',
            'umfang' => 'scope',
            'umweltwaerme' => 'environmentalHeat',
            'version' => 'version',
            'visible' => 'visible',
            'vorne' => 'front',
            'wachdienst' => 'securityService',
            'waermelieferung' => 'heatSupply',
            'walmdach' => 'hipRoof',
            'wanne' => 'bathtub',
            'wasserElektro' => 'waterElectric',
            'wasserenergie' => 'waterEnergy',
            'waz' => 'waz',
            'wert' => 'worth',
            'west' => 'west',
            'windenergie' => 'windEnergy',
            'wohnen' => 'living',
            'wohnungtyp' => 'apartmentType',
            'zeiteinheit' => 'timeUnit',
            'zentral' => 'central',
            'zimmertyp' => 'roomType',
            'zinsTyp' => 'interestType',
            'zustandArt' => 'conditionType',
            default => throw new InvalidArgumentException('Unknown key: '.$key),
        };
    }

    public static function translateProperties(string $key): string
    {
        return match ($key) {
            'abdatum' => 'fromDate',
            'abstand' => 'distance',
            'abstellraum' => 'storageRoom',
            'adressfreigabe' => 'addressRelease',
            'aktenzeichen' => 'fileNumber',
            'aktion' => 'action',
            'aktivBis' => 'activeTo',
            'aktivVon' => 'activeFrom',
            'alsFerien' => 'asHoliday',
            'alter' => 'age',
            'altlasten' => 'contamination',
            'amtsgericht' => 'districtCourt',
            'anbieter' => 'provider',
            'anbieternr' => 'providerNumber',
            'angeschlGastronomie' => 'attachedGastronomy',
            'anhaenge' => 'attachments',
            'anhang' => 'attachment',
            'anhanginhalt' => 'attachmentContent',
            'anhangtitel' => 'attachmentTitle',
            'anrede' => 'salutation',
            'anredeBrief' => 'letterSalutation',
            'anzahlBadezimmer' => 'numberOfBathrooms',
            'anzahlBalkone' => 'numberOfBalconies',
            'anzahlBetten' => 'numberOfBeds',
            'anzahlEtagen' => 'numberOfFloors',
            'anzahlGewerbeeinheiten' => 'numberOfCommercialUnits',
            'anzahlLogia' => 'numberOfLoggias',
            'anzahlSchlafzimmer' => 'numberOfBedrooms',
            'anzahlSepWc' => 'numberOfSeparateToilets',
            'anzahlStellplaetze' => 'numberOfParkingSpaces',
            'anzahlTagungsraeume' => 'numberOfMeetingRooms',
            'anzahlTerrassen' => 'numberOfTerraces',
            'anzahlWohnSchlafzimmer' => 'numberOfLivingBedrooms',
            'anzahlWohneinheiten' => 'numberOfResidentialUnits',
            'anzahlZimmer' => 'numberOfRooms',
            'ausbaustufe' => 'developmentStage',
            'ausblick' => 'view',
            'ausnuetzungsziffer' => 'floorAreaRatio',
            'ausrichtBalkonTerrasse' => 'balconyTerraceOrientation',
            'aussenCourtage' => 'externalCommission',
            'ausstattBeschr' => 'equipmentDescription',
            'ausstattKategorie' => 'equipmentCategory',
            'ausstattung' => 'equipment',
            'ausstelldatum' => 'issueDate',
            'bad' => 'bathroom',
            'balkonTerrasseFlaeche' => 'balconyTerraceArea',
            'barrierefrei' => 'barrierFree',
            'baujahr' => 'yearOfConstruction',
            'bauweise' => 'constructionMethod',
            'bauzone' => 'constructionZone',
            'bebaubarNach' => 'developableAccordingTo',
            'befeuerung' => 'heating',
            'beginnAngebotsphase' => 'startOfOfferPhase',
            'beginnBietzeit' => 'startOfBiddingTime',
            'beheizbareFlaeche' => 'heatedArea',
            'berufsaufsichtsbehoerde' => 'professionalSupervisoryAuthority',
            'besichtigungstermin' => 'viewingAppointment',
            'besichtigungstermin2' => 'viewingAppointment2',
            'betriebskostennetto' => 'netOperatingCosts',
            'bewertung' => 'evaluation',
            'bgf' => 'grossFloorArea',
            'bibliothek' => 'library',
            'bieterverfahren' => 'biddingProcess',
            'bisdatum' => 'toDate',
            'bmz' => 'floorSpaceIndex',
            'boden' => 'floor',
            'branchen' => 'industries',
            'brauereibindung' => 'breweryTie',
            'breitbandZugang' => 'broadbandAccess',
            'bueroPraxen' => 'officesPractices',
            'bueroflaeche' => 'officeArea',
            'bueroteilflaeche' => 'partialOfficeArea',
            'bundesland' => 'state',
            'check' => 'check',
            'courtageHinweis' => 'commissionNote',
            'dachboden' => 'attic',
            'dachbodenflaeche' => 'atticArea',
            'dachform' => 'roofShape',
            'daten' => 'data',
            'denkmalgeschuetzt' => 'listedBuilding',
            'distanzen' => 'distances',
            'distanzenSport' => 'sportDistances',
            'dreizeiler' => 'threeLines',
            'dvVerkabelung' => 'dataProcessingCabling',
            'dvbt' => 'digitalTerrestrialTV',
            'einliegerwohnung' => 'grannyFlat',
            'einzelhandel' => 'retail',
            'emailDirekt' => 'directEmail',
            'emailFeedback' => 'feedbackEmail',
            'emailPrivat' => 'privateEmail',
            'emailSonstige' => 'otherEmail',
            'emailZentrale' => 'centralEmail',
            'endeBietzeit' => 'endOfBiddingTime',
            'endenergiebedarf' => 'finalEnergyDemand',
            'energiepass' => 'energyCertificate',
            'energietyp' => 'energyType',
            'energieverbrauchkennwert' => 'energyConsumptionValue',
            'epart' => 'energyCertificateType',
            'epasstext' => 'energyCertificateText',
            'erbpacht' => 'leasehold',
            'erschliessung' => 'development',
            'erschliessungUmfang' => 'developmentScope',
            'erschliessungskosten' => 'developmentCosts',
            'etage' => 'floor',
            'evbnetto' => 'netUnitValue',
            'fahrradraum' => 'bicycleRoom',
            'fahrstuhl' => 'elevator',
            'feld' => 'field',
            'fensterfront' => 'windowFront',
            'fensterfrontQm' => 'windowFrontSqm',
            'fgeeklasse' => 'energyEfficiencyClass',
            'fgeewert' => 'energyEfficiencyValue',
            'firma' => 'company',
            'firmenanschrift' => 'companyAddress',
            'firmenname' => 'companyName',
            'flaechebis' => 'areaTo',
            'flaechen' => 'areas',
            'flaechevon' => 'areaFrom',
            'flur' => 'corridor',
            'flurstueck' => 'parcel',
            'format' => 'format',
            'foto' => 'photo',
            'freiflaeche' => 'openSpace',
            'freitextPreis' => 'freeTextPrice',
            'freitexte' => 'freeTexts',
            'freitextfeld' => 'freeTextField',
            'freizeitimmobilieGewerblich' => 'commercialLeisureProperty',
            'gaestewc' => 'guestToilet',
            'gartenflaeche' => 'gardenArea',
            'gartennutzung' => 'gardenUse',
            'gastgewerbe' => 'hospitality',
            'gastroflaeche' => 'gastronomyArea',
            'gastterrasse' => 'guestTerrace',
            'gebaeudeart' => 'buildingType',
            'geg2018' => 'buildingEnergyAct2018',
            'gemarkung' => 'cadastralDistrict',
            'gemeindecode' => 'municipalityCode',
            'geo' => 'geo',
            'geokoordinaten' => 'geoCoordinates',
            'gesamtbelastungbrutto' => 'totalCostGross',
            'gesamtbelastungnetto' => 'totalCostNet',
            'gesamtflaeche' => 'totalArea',
            'gesamtkostenprom2von' => 'totalCostsPerSqmFrom',
            'gesamtmietebrutto' => 'totalRentGross',
            'gesamtmietenetto' => 'totalRentNet',
            'geschaeftsguthaben' => 'businessAssets',
            'geschlecht' => 'gender',
            'gewerblicheNutzung' => 'commercialUse',
            'gfz' => 'floorAreaRatio',
            'grundstueck' => 'plot',
            'grundstuecksflaeche' => 'plotArea',
            'grundstuecksfront' => 'plotFront',
            'gruppenKennung' => 'groupIdentifier',
            'gruppennummer' => 'groupNumber',
            'grz' => 'siteOccupancyIndex',
            'gueltigBis' => 'validUntil',
            'hallenLagerProd' => 'hallsStorageProduction',
            'hallenhoehe' => 'hallHeight',
            'handelsregister' => 'commercialRegister',
            'handelsregisterNr' => 'commercialRegisterNumber',
            'hauptmietzinsnetto' => 'netMainRent',
            'haus' => 'house',
            'hausgeld' => 'maintenanceFee',
            'hausnummer' => 'houseNumber',
            'haustiere' => 'pets',
            'hebebuehne' => 'liftPlatform',
            'heizkosten' => 'heatingCosts',
            'heizkostenEnthalten' => 'heatingCostsIncluded',
            'heizkostennetto' => 'netHeatingCosts',
            'heizungsart' => 'heatingType',
            'hochhaus' => 'highRise',
            'hoechstgebotZeigen' => 'showHighestBid',
            'hwbklasse' => 'heatingDemandClass',
            'hwbwert' => 'heatingDemandValue',
            'immobilie' => 'property',
            'immobilientreuhaenderid' => 'propertyTrusteeId',
            'impressum' => 'imprint',
            'impressumStrukt' => 'imprintStructure',
            'infrastruktur' => 'infrastructure',
            'innenCourtage' => 'internalCommission',
            'jahrgang' => 'year',
            'kabelSatTv' => 'cableSatelliteTV',
            'kabelkanaele' => 'cableChannels',
            'kaltmiete' => 'coldRent',
            'kamin' => 'fireplace',
            'kantineCafeteria' => 'canteenCafeteria',
            'kartenMakro' => 'macroMap',
            'kartenMikro' => 'microMap',
            'kaufpreis' => 'purchasePrice',
            'kaufpreisProQm' => 'purchasePricePerSqm',
            'kaufpreisbrutto' => 'purchasePriceGross',
            'kaufpreisnetto' => 'purchasePriceNet',
            'kaution' => 'deposit',
            'kautionText' => 'depositText',
            'kellerflaeche' => 'basementArea',
            'kennungUrsprung' => 'originIdentifier',
            'klimatisiert' => 'airConditioned',
            'kontaktperson' => 'contactPerson',
            'kran' => 'crane',
            'kubatur' => 'cubature',
            'kueche' => 'kitchen',
            'ladenflaeche' => 'shopArea',
            'lage' => 'location',
            'lageGebiet' => 'areaLocation',
            'lageImBau' => 'locationInBuilding',
            'lagerflaeche' => 'storageArea',
            'land' => 'country',
            'landUndForstwirtschaft' => 'agricultureAndForestry',
            'laufzeit' => 'duration',
            'letztemodernisierung' => 'lastModernization',
            'lizenzkennung' => 'licenseIdentifier',
            'luftbildern' => 'aerialPhotos',
            'master' => 'master',
            'maxMietdauer' => 'maxRentalPeriod',
            'maxPersonen' => 'maxPersons',
            'mieteinnahmenIst' => 'actualRentalIncome',
            'mieteinnahmenSoll' => 'targetRentalIncome',
            'mietpreisProQm' => 'rentPricePerSqm',
            'mietzuschlaege' => 'rentSurcharges',
            'minMietdauer' => 'minRentalPeriod',
            'mindestpreis' => 'minimumPrice',
            'mitwarmwasser' => 'withHotWater',
            'modus' => 'mode',
            'moebliert' => 'furnished',
            'monatlichekostenbrutto' => 'monthlyCostsGross',
            'monatlichekostennetto' => 'monthlyCostsNet',
            'mwstGesamt' => 'totalVAT',
            'mwstSatz' => 'vatRate',
            'name' => 'name',
            'nebenkosten' => 'additionalCosts',
            'nebenkostenprom2von' => 'additionalCostsPerSqmFrom',
            'nettokaltmiete' => 'netColdRent',
            'nettomieteprom2von' => 'netRentPerSqmFrom',
            'nettorendite' => 'netYield',
            'nettorenditeIst' => 'actualNetYield',
            'nettorenditeSoll' => 'targetNetYield',
            'nichtraucher' => 'nonSmoker',
            'nutzflaeche' => 'usableArea',
            'nutzungsart' => 'typeOfUse',
            'objektText' => 'propertyText',
            'objektadresseFreigeben' => 'releasePropertyAddress',
            'objektart' => 'propertyType',
            'objektartZusatz' => 'propertyTypeAdditional',
            'objektbeschreibung' => 'propertyDescription',
            'objektkategorie' => 'propertyCategory',
            'objektnrExtern' => 'externalPropertyNumber',
            'objektnrIntern' => 'internalPropertyNumber',
            'objekttitel' => 'propertyTitle',
            'openimmoAnid' => 'openImmoAnid',
            'openimmoObid' => 'openImmoObjectId',
            'ort' => 'city',
            'pacht' => 'lease',
            'parken' => 'parking',
            'pauschalmiete' => 'flatRent',
            'personennummer' => 'personNumber',
            'pfad' => 'path',
            'plaetzeGastraum' => 'diningRoomSeats',
            'plz' => 'postalCode',
            'position' => 'position',
            'postfOrt' => 'poBoxCity',
            'postfPlz' => 'poBoxPostalCode',
            'postfach' => 'poBox',
            'preisZeiteinheit' => 'priceTimeUnit',
            'preisZeitraumBis' => 'priceTimeRangeTo',
            'preisZeitraumVon' => 'priceTimeRangeFrom',
            'preise' => 'prices',
            'primaerenergietraeger' => 'primaryEnergySource',
            'provisionTeilen' => 'commissionSplit',
            'provisionbrutto' => 'commissionGross',
            'provisionnetto' => 'commissionNet',
            'provisionspflichtig' => 'commissionRequired',
            'raeumeVeraenderbar' => 'roomsModifiable',
            'rampe' => 'ramp',
            'referenzId' => 'referenceId',
            'regionalerZusatz' => 'regionalAddition',
            'richtpreis' => 'guidePrice',
            'richtpreisprom2' => 'guidePricePerSqm',
            'rolladen' => 'shutters',
            'rollstuhlgerecht' => 'wheelchairAccessible',
            'ruecklagenetto' => 'reservesNet',
            'sauna' => 'sauna',
            'seniorengerecht' => 'seniorFriendly',
            'serviceleistungen' => 'services',
            'sicherheitstechnik' => 'securityTechnology',
            'sonstflaeche' => 'otherArea',
            'sonstige' => 'other',
            'sonstigeAngaben' => 'otherInformation',
            'sonstigekostennetto' => 'otherCostsNet',
            'sonstigemietenetto' => 'otherRentNet',
            'sporteinrichtungen' => 'sportsFacilities',
            'sprache' => 'language',
            'standVom' => 'statusFrom',
            'stellplatzart' => 'parkingSpaceType',
            'steuernummer' => 'taxNumber',
            'stpCarport' => 'parkingCarport',
            'stpDuplex' => 'parkingDuplex',
            'stpFreiplatz' => 'parkingOutdoor',
            'stpGarage' => 'parkingGarage',
            'stpParkhaus' => 'parkingMultiStorey',
            'stpSonstige' => 'parkingOther',
            'stpTiefgarage' => 'parkingUnderground',
            'strasse' => 'street',
            'stromanschlusswert' => 'electricityConnectionValue',
            'stromwert' => 'electricityValue',
            'summemietenetto' => 'totalRentNet',
            'swimmingpool' => 'swimmingPool',
            'teekueche' => 'kitchenette',
            'teilbarAb' => 'divisibleFrom',
            'telDurchw' => 'phoneExtension',
            'telFax' => 'faxNumber',
            'telHandy' => 'mobileNumber',
            'telPrivat' => 'privatePhoneNumber',
            'telSonstige' => 'otherPhoneNumber',
            'telZentrale' => 'centralPhoneNumber',
            'telefon' => 'phone',
            'telefonFerienimmobilie' => 'holidayPropertyPhone',
            'titel' => 'title',
            'typ' => 'type',
            'uebertragung' => 'transfer',
            'umsstId' => 'vatId',
            'umtsEmpfang' => 'umtsReception',
            'unterkellert' => 'basement',
            'url' => 'url',
            'userDefinedAnyfield' => 'userDefinedAnyfield',
            'userDefinedExtend' => 'userDefinedExtend',
            'userDefinedSimplefield' => 'userDefinedSimplefield',
            'verfuegbarAb' => 'availableFrom',
            'verkaufsflaeche' => 'salesArea',
            'verkaufstatus' => 'salesStatus',
            'verkehrswert' => 'marketValue',
            'vermarktungsart' => 'marketingType',
            'vermietbareFlaeche' => 'rentableArea',
            'vermietet' => 'rented',
            'versteigerung' => 'auction',
            'versteigerungstermin' => 'auctionDate',
            'vertretungsberechtigter' => 'authorizedRepresentative',
            'verwaltungObjekt' => 'propertyManagement',
            'verwaltungTechn' => 'technicalManagement',
            'verwaltungsflaeche' => 'administrativeArea',
            'virtuelletour' => 'virtualTour',
            'vorname' => 'firstName',
            'waehrung' => 'currency',
            'waermewert' => 'heatValue',
            'warmmiete' => 'warmRent',
            'waschTrockenraum' => 'laundryDryingRoom',
            'wbsSozialwohnung' => 'socialHousing',
            'weitereAdresse' => 'additionalAddress',
            'weiteres' => 'additional',
            'weitergabeGenerell' => 'generalForwarding',
            'weitergabeNegativ' => 'negativeForwarding',
            'weitergabePositiv' => 'positiveForwarding',
            'wellnessbereich' => 'wellnessArea',
            'wert' => 'value',
            'wertklasse' => 'valueClass',
            'wgGeeignet' => 'suitableForSharedFlat',
            'wintergarten' => 'winterGarden',
            'wohnflaeche' => 'livingArea',
            'wohnung' => 'apartment',
            'wohnungsnr' => 'apartmentNumber',
            'xFache' => 'xTimes',
            'zimmer' => 'rooms',
            'zinshausRenditeobjekt' => 'apartmentBuildingInvestmentProperty',
            'zugang' => 'access',
            'zulieferung' => 'supply',
            'zusatzfeld' => 'additionalField',
            'zusatztermin' => 'additionalDate',
            'zustand' => 'condition',
            'zustandAngaben' => 'conditionInformation',
            'zvtermin' => 'forcedSaleDate',
            'zwangsversteigerung' => 'forcedSale',
            'zzgMehrwertsteuer' => 'plusVAT',
            '' => '',
            default => throw new InvalidArgumentException('Unknown key: '.$key),
        };
    }

    public static function translateConstants(string $key): string
    {
        return match ($key) {
            '1A' => 'PRIME',
            '1B' => 'SECONDARY',
            '34_NACHBARSCHAFT' => 'NEIGHBORHOOD',
            '35_AUSSENGEBIET' => 'OUTLYING_AREA',
            'ABRISSOBJEKT' => 'DEMOLITION_PROPERTY',
            'ABSOLUT' => 'ABSOLUTE',
            'ACKERBAU' => 'ARABLE_FARMING',
            'ALTBAU' => 'OLD_BUILDING',
            'ANBIETERLOGO' => 'PROVIDER_LOGO',
            'ANBOBJURL' => 'PROPERTY_URL',
            'ANWESEN' => 'ESTATE',
            'APARTMENT' => 'APARTMENT',
            'APARTMENTHAUS' => 'APARTMENT_BUILDING',
            'ATTIKAWOHNUNG' => 'PENTHOUSE_APARTMENT',
            'AUSSENANSICHTEN' => 'EXTERIOR_VIEWS',
            'AUSSIEDLERHOF' => 'SETTLER_S_FARM',
            'AUSSTELLUNGSFLAECHE' => 'EXHIBITION_SPACE',
            'AUTOBAHN' => 'HIGHWAY',
            'B_PLAN' => 'DEVELOPMENT_PLAN',
            'BAR' => 'BAR',
            'BAUERNHAUS' => 'FARMHOUSE',
            'BAUERNHOF' => 'FARM',
            'BAUERWARTUNGSLAND' => 'EXPECTED_BUILDING_LAND',
            'BAUFAELLIG' => 'DILAPIDATED',
            'BAULAND_OHNE_B_PLAN' => 'BUILDABLE_LAND_WITHOUT_DEVELOPMENT_PLAN',
            'BEDARF' => 'DEMAND',
            'BEI_BESICHTIGUNG' => 'ON_INSPECTION',
            'BERGE' => 'MOUNTAINS',
            'BERGHUETTE' => 'MOUNTAIN_HUT',
            'BETREUTES_WOHNEN' => 'ASSISTED_LIVING',
            'BILD' => 'IMAGE',
            'BOOTSLIEGEPLATZ' => 'BOAT_MOORING',
            'BUEROFLAECHE' => 'OFFICE_SPACE',
            'BUEROGEBAEUDE' => 'OFFICE_BUILDING',
            'BUEROHAUS' => 'OFFICE_BUILDING',
            'BUEROZENTRUM' => 'OFFICE_CENTER',
            'BUNGALOW' => 'BUNGALOW',
            'BURG' => 'CASTLE',
            'BUS' => 'BUS',
            'CAFE' => 'CAFE',
            'CARPORT' => 'CARPORT',
            'CHALET' => 'CHALET',
            'CHANGE' => 'CHANGE',
            'COWORKING' => 'COWORKING',
            'DACHGESCHOSS' => 'ATTIC',
            'DATETIME' => 'DATETIME',
            'DELETE' => 'DELETE',
            'DISCOTHEK' => 'NIGHTCLUB',
            'DOKUMENTE' => 'DOCUMENTS',
            'DOPPELGARAGE' => 'DOUBLE_GARAGE',
            'DOPPELHAUSHAELFTE' => 'SEMI_DETACHED_HOUSE',
            'DUPLEX' => 'DUPLEX',
            'EGAL' => 'ANY',
            'EINFAMILIENHAUS' => 'SINGLE_FAMILY_HOUSE',
            'EINKAUFSCENTREN' => 'SHOPPING_CENTERS',
            'EINKAUFSMOEGLICHKEITEN' => 'SHOPPING_FACILITIES',
            'EINKAUFSZENTRUM' => 'SHOPPING_CENTER',
            'EINRAUMLOKAL' => 'ONE_ROOM_ESTABLISHMENT',
            'EINZELGARAGE' => 'SINGLE_GARAGE',
            'EINZELHANDELSLADEN' => 'RETAIL_STORE',
            'EM_DIREKT' => 'DIRECT_MARKETING',
            'EM_PRIVAT' => 'PRIVATE_MARKETING',
            'EM_SONSTIGE' => 'OTHER_MARKETING',
            'EM_ZENTRALE' => 'HQ_MARKETING',
            'ENTKERNT' => 'GUTTED',
            'EPASS_SKALA' => 'ENERGY_PASS_SCALE',
            'ERDGESCHOSS' => 'GROUND_FLOOR',
            'ERSTBEZUG' => 'FIRST_OCCUPANCY',
            'ETAG' => 'ETAG',
            'ETAGE' => 'FLOOR',
            'EXTERN' => 'EXTERNAL',
            'FACTORY_OUTLET' => 'FACTORY_OUTLET',
            'FERIENHAUS' => 'HOLIDAY_HOUSE',
            'FERIENWOHNUNG' => 'HOLIDAY_APARTMENT',
            'FERNBAHNHOF' => 'LONG_DISTANCE_TRAIN_STATION',
            'FERNE' => 'DISTANCE',
            'FERTIGHAUS' => 'PREFABRICATED_HOUSE',
            'FILM' => 'MOVIE',
            'FILMLINK' => 'MOVIE_LINK',
            'FINCA' => 'FINCA',
            'FLUGHAFEN' => 'AIRPORT',
            'FREIFLAECHEN' => 'OPEN_SPACES',
            'FREIPLATZ' => 'OPEN_SPACE',
            'FREIZEIT' => 'LEISURE',
            'FREIZEITANLAGE' => 'LEISURE_FACILITY',
            'GALERIE' => 'GALLERY',
            'GARAGE' => 'GARAGE',
            'GARTENBAU' => 'HORTICULTURE',
            'GAS' => 'GAS',
            'GASTRONOMIE_UND_WOHNUNG' => 'GASTRONOMY_AND_APARTMENT',
            'GASTRONOMIE' => 'GASTRONOMY',
            'GASTSTAETTEN' => 'RESTAURANTS',
            'GEHOBEN' => 'UPSCALE',
            'GEPFLEGT' => 'WELL_MAINTAINED',
            'GESAMTSCHULE' => 'COMPREHENSIVE_SCHOOL',
            'GESCHAEFTSHAUS' => 'BUSINESS_BUILDING',
            'GEWERBE' => 'COMMERCIAL',
            'GEWERBEPARK' => 'BUSINESS_PARK',
            'GRUNDRISS' => 'FLOOR_PLAN',
            'GRUNDSCHULE' => 'ELEMENTARY_SCHOOL',
            'GYMNASIUM' => 'HIGH_SCHOOL',
            'HALLE' => 'HALL',
            'HAUPTSCHULE' => 'MAIN_SCHOOL',
            'HERRENHAUS' => 'MANOR_HOUSE',
            'HOCHREGALLAGER' => 'HIGH_BAY_WAREHOUSE',
            'HOTELS' => 'HOTELS',
            'INDUSTRIE' => 'INDUSTRIAL',
            'INDUSTRIEANLAGEN' => 'INDUSTRIAL_FACILITIES',
            'INDUSTRIEHALLE' => 'INDUSTRIAL_HALL',
            'INNENANSICHTEN' => 'INTERIOR_VIEWS',
            'INTERN' => 'INTERNAL',
            'JAGD_UND_FORSTWIRTSCHAFT' => 'HUNTING_AND_FORESTRY',
            'JAGDREVIER' => 'HUNTING_GROUND',
            'JAHR' => 'YEAR',
            'KARTEN_LAGEPLAN' => 'MAPS_SITE_PLAN',
            'KAUFHAUS' => 'DEPARTMENT_STORE',
            'KEIN_BAULAND' => 'NOT_BUILDABLE_LAND',
            'KEINE_ANGABE' => 'NO_INFORMATION',
            'KINDERGAERTEN' => 'KINDERGARTENS',
            'KIOSK' => 'KIOSK',
            'KRANKENHAUS' => 'HOSPITAL',
            'KUEHLHAUS' => 'COLD_STORAGE',
            'LADENLOKAL' => 'SHOP',
            'LAENDERSPEZIFISCH' => 'COUNTRY_SPECIFIC',
            'LAGER_MIT_FREIFLAECHE' => 'WAREHOUSE_WITH_OPEN_SPACE',
            'LAGER' => 'WAREHOUSE',
            'LAGERFLAECHEN' => 'STORAGE_AREAS',
            'LAND_FORSTWIRSCHAFT' => 'AGRICULTURAL_FORESTRY',
            'LANDHAUS' => 'COUNTRY_HOUSE',
            'LANDWIRTSCHAFTLICHE_BETRIEBE' => 'AGRICULTURAL_ENTERPRISES',
            'LAUBE_DATSCHE_GARTENHAUS' => 'SUMMER_HOUSE',
            'LINKS' => 'LINKS',
            'LOFT_ATELIER' => 'LOFT_ATELIER',
            'LOFT_STUDIO_ATELIER' => 'LOFT_STUDIO_ATELIER',
            'LUXUS' => 'LUXURY',
            'MAISONETTE' => 'MAISONETTE',
            'MD5' => 'MD5',
            'MEER' => 'SEA',
            'MEHRFAMILIENHAUS' => 'MULTI_FAMILY_HOUSE',
            'MISCH_GEMISCHT' => 'MIXED',
            'MODERNISIERT' => 'MODERNIZED',
            'MONAT' => 'MONTH',
            'NACH_VEREINBARUNG' => 'BY_AGREEMENT',
            'NAHERHOLUNG' => 'LOCAL_RECREATION',
            'NEBENZENTRUM' => 'SECONDARY_CENTER',
            'NEUBAU' => 'NEW_CONSTRUCTION',
            'NEUWERTIG' => 'AS_NEW',
            'NEW' => 'NEW',
            'NICHT_NOETIG' => 'NOT_NECESSARY',
            'NICHTWOHN' => 'NON_RESIDENTIAL',
            'NUR_FRAU' => 'FEMALE_ONLY',
            'NUR_MANN' => 'MALE_ONLY',
            'OFFEN' => 'OPEN',
            'OFFLINE' => 'OFFLINE',
            'OHNE' => 'WITHOUT',
            'ONLINE' => 'ONLINE',
            'ORTSLAGE' => 'LOCATION',
            'ORTSUEBLICHERSCHLOSSEN' => 'USUALLY_DEVELOPED',
            'PANORAMA' => 'PANORAMA',
            'PARKHAUS' => 'PARKING_GARAGE',
            'PARKPLATZ_STROM' => 'PARKING_SPACE_WITH_ELECTRICITY',
            'PENSIONEN' => 'GUESTHOUSES',
            'PENTHOUSE' => 'PENTHOUSE',
            'PFLEGEHEIM' => 'NURSING_HOME',
            'PRAXIS' => 'PRACTICE',
            'PRAXISFLAECHE' => 'PRACTICE_AREA',
            'PRAXISHAUS' => 'PRACTICE_HOUSE',
            'PRODUKTION' => 'PRODUCTION',
            'PROJEKTIERT' => 'PLANNED',
            'PROZENT' => 'PERCENT',
            'QRCODE' => 'QRCODE',
            'RAUCHERLOKAL' => 'SMOKING_ESTABLISHMENT',
            'REALSCHULE' => 'INTERMEDIATE_SCHOOL',
            'REFERENZ' => 'REFERENCE',
            'REIHENECK' => 'CORNER_TERRACE',
            'REIHENEND' => 'END_TERRACE',
            'REIHENHAUS' => 'TOWNHOUSE',
            'REIHENMITTEL' => 'MID_TERRACE',
            'REITERHOEFE' => 'EQUESTRIAN_FARMS',
            'REMOTE' => 'REMOTE',
            'RESERVIERT' => 'RESERVED',
            'RESTAURANT' => 'RESTAURANT',
            'RESTHOF' => 'FARMHOUSE',
            'ROHBAU' => 'SHELL_CONSTRUCTION',
            'ROHDACHBODEN' => 'RAW_ATTIC',
            'RUSTICO' => 'RUSTICO',
            'SANATORIUM' => 'SANATORIUM',
            'SANIERUNGSBEDUERFTIG' => 'IN_NEED_OF_RENOVATION',
            'SB_MAERKTE' => 'SELF_SERVICE_MARKETS',
            'SCHEUNEN' => 'BARNS',
            'SCHLOSS' => 'CASTLE',
            'SEE' => 'LAKE',
            'SEELIEGENSCHAFT' => 'LAKESIDE_PROPERTY',
            'SENIORENHEIM' => 'SENIOR_CITIZEN_HOME',
            'SERVICE' => 'SERVICE',
            'SHARED_OFFICE' => 'SHARED_OFFICE',
            'SIEDLUNG' => 'SETTLEMENT',
            'SKIGEBIET' => 'SKI_AREA',
            'SONDERNUTZUNG' => 'SPECIAL_USE',
            'SONSTIGE_LANDWIRTSCHAFTSIMMOBILIEN' => 'OTHER_AGRICULTURAL_PROPERTIES',
            'SONSTIGE' => 'OTHER',
            'SONSTIGES' => 'OTHER',
            'SOUTERRAIN' => 'BASEMENT',
            'SPEDITIONSLAGER' => 'FORWARDING_WAREHOUSE',
            'SPORTANLAGEN' => 'SPORTS_FACILITIES',
            'STADTHAUS' => 'CITY_HOUSE',
            'STADTRAND' => 'OUTSKIRTS',
            'STADTTEIL' => 'DISTRICT',
            'STADTZENTRUM' => 'CITY_CENTER',
            'STANDARD' => 'STANDARD',
            'STELLPLATZ' => 'PARKING_SPACE',
            'STRAND' => 'BEACH',
            'STRANDHAUS' => 'BEACH_HOUSE',
            'STROM' => 'ELECTRICITY',
            'TAG' => 'DAY',
            'TANKSTELLE' => 'GAS_STATION',
            'TEICH_UND_FISCHWIRTSCHAFT' => 'POND_AND_FISHERY',
            'TEIL_SANIERT' => 'PARTIALLY_RENOVATED',
            'TEIL_VOLLRENOVIERT' => 'PARTIALLY_FULLY_RENOVATED',
            'TEIL_VOLLRENOVIERUNGSBED' => 'PARTIAL_FULL_RENOVATION_NEEDED',
            'TEIL_VOLLSANIERT' => 'PARTIALLY_FULLY_REFURBISHED',
            'TEIL' => 'PARTIAL',
            'TEILERSCHLOSSEN' => 'PARTIALLY_DEVELOPED',
            'TEL_DURCHW' => 'DIRECT_LINE',
            'TEL_FAX' => 'FAX',
            'TEL_HANDY' => 'MOBILE_PHONE',
            'TEL_PRIVAT' => 'PRIVATE_PHONE',
            'TEL_SONSTIGE' => 'OTHER_PHONE',
            'TEL_ZENTRALE' => 'HQ_TELEPHONE',
            'TERRASSEN' => 'TERRACES',
            'TEXT' => 'TEXT',
            'TIEFGARAGE' => 'UNDERGROUND_GARAGE',
            'TIEFGARAGENSTELLPLATZ' => 'UNDERGROUND_PARKING_SPACE',
            'TITELBILD' => 'COVER_IMAGE',
            'TK' => 'TELECOMMUNICATION',
            'UNERSCHLOSSEN' => 'UNDEVELOPED',
            'US_BAHN' => 'SUBWAY',
            'VERBRAUCH' => 'CONSUMPTION',
            'VERBRAUCHERMAERKTE' => 'CONSUMER_MARKETS',
            'VERBRAUCHERMARKT' => 'SUPERMARKET',
            'VERGNUEGUNGSPARKS_UND_CENTER' => 'AMUSEMENT_PARKS_AND_CENTERS',
            'VERKAUFSFLAECHE' => 'SALES_AREA',
            'VERKAUFT' => 'SOLD',
            'VIEHWIRTSCHAFT' => 'LIVESTOCK_FARMING',
            'VILLA' => 'VILLA',
            'VOLL_SANIERT' => 'FULLY_RENOVATED',
            'VOLL' => 'FULL',
            'VOLLERSCHLOSSEN' => 'FULLY_DEVELOPED',
            'WANDERGEBIETE' => 'HIKING_AREAS',
            'WASSER' => 'WATER',
            'WEINBAU' => 'VITICULTURE',
            'WEITERE_BEHERBERGUNGSBETRIEBE' => 'OTHER_ACCOMMODATION_FACILITIES',
            'WERKSTATT' => 'WORKSHOP',
            'WOCHE' => 'WEEK',
            'WOHN_UND_GESCHAEFTSHAUS' => 'RESIDENTIAL_AND_COMMERCIAL_BUILDING',
            'WOHN' => 'RESIDENTIAL',
            'WOHNANLAGEN' => 'HOUSING_ESTATES',
            'WOHNEN' => 'LIVING',
            'ZENTRUM' => 'CENTER',
            'ZIMMER' => 'ROOM',
            'ZWEIFAMILIENHAUS' => 'TWO_FAMILY_HOUSE',

            // Prefixes
            'AKTIONART' => 'ACTION_TYPE',
            'ALTER_ATTR' => 'AGE_ATTRIBUTE',
            'ART' => 'TYPE',
            'AUSSTATT_KATEGORIE' => 'EQUIPMENT_CATEGORY',
            'BEBAUBAR_ATTR' => 'BUILDABLE_ATTRIBUTE',
            'BLICK' => 'VIEW',
            'BUERO_TYP' => 'OFFICE_TYPE',
            'CTYPE' => 'CONTACT_TYPE',
            'DISTANZ_ZU' => 'DISTANCE_TO',
            'DISTANZ_ZU_SPORT' => 'DISTANCE_TO_SPORT',
            'EMAILART' => 'EMAIL_TYPE',
            'EPART' => 'PARTITION',
            'ERSCHL_ATTR' => 'DEVELOPMENT_ATTRIBUTE',
            'FREIZEIT_TYP' => 'LEISURE_TYPE',
            'GASTGEW_TYP' => 'HOSPITALITY_TYPE',
            'GEBIETE' => 'AREAS',
            'GEBAEUDEART' => 'BUILDING_TYPE',
            'GESCHL_ATTR' => 'GENDER_ATTRIBUTE',
            'GRUNDST_TYP' => 'PROPERTY_TYPE',
            'GRUPPE' => 'GROUP',
            'HALLEN_TYP' => 'HALL_TYPE',
            'HANDEL_TYP' => 'TRADE_TYPE',
            'HAUSTYP' => 'HOUSE_TYPE',
            'ISO_LAND' => 'ISO_COUNTRY',
            'ISO_WAEHRUNG' => 'ISO_CURRENCY',
            'JAHRGANG' => 'VINTAGE',
            'KELLER' => 'CELLAR',
            'LAND_TYP' => 'LAND_TYPE',
            'LOCATION' => 'LOCATION',
            'MAX_DAUER' => 'MAX_DURATION',
            'MIN_DAUER' => 'MIN_DURATION',
            'MODUS' => 'MODE',
            'MOEB' => 'FURNISHED',
            'PARKEN_TYP' => 'PARKING_TYPE',
            'PERIODE' => 'PERIOD',
            'PLATZART' => 'PLACE_TYPE',
            'SONSTIGE_TYP' => 'OTHER_TYPE',
            'STAND' => 'CONDITION',
            'TELEFONART' => 'PHONE_TYPE',
            'UMFANG' => 'SCOPE',
            'WERT' => 'VALUE',
            'WOHNUNGTYP' => 'APARTMENT_TYPE',
            'ZIMMERTYP' => 'ROOM_TYPE',
            'ZEITEINHEIT' => 'TIME_UNIT',
            'ZINS_TYP' => 'INTEREST_TYPE',
            'ZUSTAND_ART' => 'CONDITION_TYPE',
            default => $key,
        };
    }
}
